spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true
   data:
      mongodb:
         host: ${MONGO_HOST}
         port: ${CCOMS_DATABASE_PORT}
         database: ${MONGO_INITDB_DATABASE}
         username: ${MONGO_INITDB_ROOT_USERNAME}
         password: ${MONGO_INITDB_ROOT_PASSWORD}
server:
   port: ${CCOMS_EMP_PORT}
