spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true
   data:
      mongodb:
         host: db.mongo.com
         port: ${CCOMS_DATABASE_PORT}
         database: ${CCOMS_DATABASE_SERVICENAME}
         username: ${CCOMS_DATABASE_USERNAME}
         password: ${CCOMS_DATABASE_PASSWORD}
server:
  port: ${CCOMS_ORG_PORT}

emp:
   service:
      url:  http://emp.ccoms.com:${CCOMS_EMP_PORT}
dept:
   service:
       url: http://dept.ccoms.com:${CCOMS_DEPT_PORT}

