spring:
   jackson:
      serialization:
         INDENT_OUTPUT: true
   data:
      mongodb:
         host: ${MONGO_HOST}
         port: ${CCOMS_DATABASE_PORT}
         database: ${CCOMS_DATABASE_SERVICENAME}
         username: ${CCOMS_DATABASE_USERNAME}
         password: ${CCOMS_DATABASE_PASSWORD}
server:
  port: ${CCOMS_DEPT_PORT}

emp:
   service:
      url: http://${EMP_HOST}:${CCOMS_EMP_PORT}

